---
- hosts: localhost
  name: "{{ tower_job_template_name }}"
  gather_facts: false
  collections:
  - netapp.ontap
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
    state: absent
    https: true
    validate_certs: false
  tasks:
  - na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volume_name }}"
      vserver: "{{ vserver }}"
      <<: *login
