---
- hosts: localhost
  name: "{{ tower_job_template_name }}"
  gather_facts: false
  collections:
  - netapp.ontap
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
    state: present
    https: true
    validate_certs: false
  tasks:
  - name: Get Source Cluster name
    na_ontap_info:
      gather_subset: cluster_identity_info
      <<: *login
    register: netapp_info
  - name: Store Source Cluster name
    set_fact:
      local_cluster: "{{ netapp_info.ontap_info.cluster_identity_info[item].cluster_name }}"
    loop: "{{ netapp_info.ontap_info.cluster_identity_info|list }}"
  - name: Get Destination Cluster name
    na_ontap_info:
      gather_subset: cluster_identity_info
      <<: *login
      hostname: "{{ dest_netapp_hostname }}"
    register: netapp_info
  - name: Store Destination Cluster name
    set_fact:
      peer_cluster: "{{ netapp_info.ontap_info.cluster_identity_info[item].cluster_name }}"
    loop: "{{ netapp_info.ontap_info.cluster_identity_info|list }}"
  - name: Create Vserver peer
    na_ontap_vserver_peer:
      state: present
      peer_vserver: "{{ peer_vserver }}"
      peer_cluster: "{{ peer_cluster }}"
      #local_name_for_peer: "{{ local_vserver }}"
      #local_name_for_source: "{{ local_cluster }}"
      vserver: "{{ local_vserver }}"
      applications: ['snapmirror']
      <<: *login
      dest_hostname: "{{ dest_netapp_hostname }}"
